name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH }}  # Используем секрет PUSH
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migration
        run: python migrate_json_to_sqlite.py
      - name: Commit and push SQLite database
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add database/bot.db
          git commit -m "Update SQLite database after migration" || echo "No changes to commit"
          git push
